import bpy

# Clear existing objects
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

# Import the original OBJ generated by Trellis (it's better to start from the raw output)
import_path = '/Users/shawn/Projects/trellis-mac/output_3d.obj'
bpy.ops.wm.obj_import(filepath=import_path)

# Ensure the imported object is selected and active
obj = bpy.context.selected_objects[0]
bpy.context.view_layer.objects.active = obj

# 1. Scale to exactly 25cm tall
bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
dim = obj.dimensions
scale_factor = 0.25 / dim.z if dim.z > 0 else 1.0
obj.scale = (scale_factor, scale_factor, scale_factor)
bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

# 2. Voxel Remesh (The ultimate fix for non-manifold AI geometry)
# This acts like a "shrink-wrap" - it ignores internal geometry and intersecting faces,
# rebuilding a brand new, perfectly watertight outer shell.
print("Running Voxel Remesh...")

# Set voxel size to 1.5mm (0.0015 meters) for high detail without massive poly counts
obj.data.remesh_voxel_size = 0.0015
bpy.ops.object.voxel_remesh()

# 3. Decimate (to ensure it's under 1 million triangles for Bambu Studio)
print("Decimating to reduce poly count...")
decimate_mod = obj.modifiers.new(name="Decimate", type='DECIMATE')
decimate_mod.ratio = 0.2 # Reduce poly count to 20% of original
bpy.ops.object.modifier_apply(modifier="Decimate")

# 4. Export to STL
export_path = '/Users/shawn/Projects/trellis-mac/bigfoot_perfected.stl'
bpy.ops.wm.stl_export(filepath=export_path)

print(f"Successfully remeshed and saved to {export_path}")
