import bpy
import bmesh
import mathutils

# Clear existing objects
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

# Import the OBJ generated by Trellis
import_path = '/Users/shawn/Projects/trellis-mac/output_3d.obj'
bpy.ops.wm.obj_import(filepath=import_path)

# Ensure the imported object is selected and active
obj = bpy.context.selected_objects[0]
bpy.context.view_layer.objects.active = obj

# 1. Scale to exactly 25cm tall
bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
dim = obj.dimensions
scale_factor = 0.25 / dim.z if dim.z > 0 else 1.0
obj.scale = (scale_factor, scale_factor, scale_factor)
bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

# 2. Fix Geometry & Make Watertight
# Switch to Edit Mode
bpy.ops.object.mode_set(mode='EDIT')
bpy.ops.mesh.select_all(action='SELECT')

# Merge vertices by distance (removes doubles)
bpy.ops.mesh.remove_doubles()

# Recalculate normals outside
bpy.ops.mesh.normals_make_consistent(inside=False)

# Optional: Try to fill holes
bpy.ops.mesh.fill_holes()

# Switch back to Object Mode
bpy.ops.object.mode_set(mode='OBJECT')

# 3. Export to STL
export_path = '/Users/shawn/Projects/trellis-mac/bigfoot_watertight.stl'
bpy.ops.wm.stl_export(filepath=export_path)

print(f"Successfully processed and saved to {export_path}")
